package main

import (
	"log"
	"net/http"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	// Replace with the actual docs package generated by swag
	// _ "github.com/ChintalaNavaneeth/shiftley/docs"
)

// @title Shiftley Gig Marketplace API
// @version 1.0
// @description This is the Shiftley.in gig marketplace backend server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.shiftley.in/support
// @contact.email support@shiftley.in

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8080
// @BasePath /api/v1
// @query.collection.format multi

// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization

func main() {
	r := gin.Default()

	// Global Middleware
	r.Use(gin.Recovery())
	r.Use(gin.Logger())

	// Health Check
	r.GET("/health", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{
			"status": "UP",
			"message": "Shiftley API is running smoothly",
		})
	})

	// V1 API Group
	v1 := r.Group("/api/v1")
	{
		// Auth Routes (Scaffold)
		auth := v1.Group("/auth")
		{
			auth.POST("/otp/send", func(c *gin.Context) {
				c.JSON(http.StatusOK, gin.H{"message": "OTP logic template"})
			})
		}
	}

	// Swagger Documentation
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	log.Println("Server starting on port 8080...")
	if err := r.Run(":8080"); err != nil {
		log.Fatalf("could not start server: %v", err)
	}
}
