version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.4
    container_name: shiftley_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../docs/schema/shiftley_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shiftley_network

  redis:
    image: redis:alpine3.23
    container_name: shiftley_redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - shiftley_network

  minio:
    image: minio/minio:latest
    container_name: shiftley_minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - shiftley_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: shiftley_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - shiftley_network

  api:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: shiftley_backend
    ports:
      - "8080:8080"
    environment:
      - APP_PORT=8080
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - BUCKET_PROFILES=${BUCKET_PROFILES}
      - BUCKET_LOGOS=${BUCKET_LOGOS}
      - BUCKET_KYC=${BUCKET_KYC}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - shiftley_network

networks:
  shiftley_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  minio_data:
